#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time

from crunner.config import ConfigLoader
from crunner.runner import Runner
from crunner.event import FileEvent
from crunner.watcher import FileWatcher


notifier, pytest, projects = ConfigLoader().load()
runner = Runner(pytest, notifier)
watchers = []
for name, settings in projects.items():
    if settings['active']:
        event = FileEvent([name, runner, settings['test_path']], regexes=['.*.py'])
        watcher = FileWatcher(settings['watch_path'], event)
        watcher.start()
        watchers.append(watcher)

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    for each in watchers:
        each.stop()
